
% DO NOT EDIT: this file is generated by M9DSE explorer 
%% Induttanze 
% Induttanze parassite di bonding interne al package 

L_d_int=9.86e-10
L_s_int=2.76e-08
L_g_int=1e-09% Induttanze parassite dei pin esterne al package (supponiamo che G e S siano uguali)

L_d_pin=5.43e-09
L_s_pin=2.76e-08
L_g_pin=3.2e-08% Induttanze parassite del PCB 

L_dH_ext=3.2e-08
L_sH_ext=3.2e-08
L_gH_ext=1.43e-08
L_dL_ext=1.43e-08
L_sL_ext=9.86e-09
L_gL_ext=1.87e-08% Induttanze parassite dei cavi per i collegamenti di Kelvin-Source 

L_Hwire=5.43e-09
L_Lwire=1.43e-08