
% DO NOT EDIT: this file is generated by M9DSE explorer 
%% Induttanze 
% Induttanze parassite di bonding interne al package 

L_d_int=3.8e-10;
L_s_int=6.41e-09;
L_g_int=2.31e-08;% Induttanze parassite dei pin esterne al package (supponiamo che G e S siano uguali)

L_d_pin=9.86e-09;
L_s_pin=1.43e-08;
L_g_pin=1e-09;% Induttanze parassite del PCB 

L_dH_ext=2.31e-08;
L_sH_ext=1.87e-08;
L_gH_ext=2.76e-08;
L_dL_ext=3.2e-08;
L_sL_ext=2.76e-08;
L_gL_ext=1.43e-08;% Induttanze parassite dei cavi per i collegamenti di Kelvin-Source 

L_Hwire=2.5e-09;
L_Lwire=1.87e-08;