spaceFileName = 'space_realigned.conf';

space = struct( ...
  'L_d_int',  linspace(1.0e-10, 1.0e-9, 10), ...
  'L_s_int',  linspace(1.0e-9,  1.0e-8, 10), ...
  'L_g_int',  linspace(5.0e-9,  5.0e-8, 10), ...
  'L_d_pin',  linspace(1.0e-9,  1.0e-8, 10), ...
  'L_s_pin',  linspace(1.0e-9,  1.0e-8, 10), ...
  'L_g_pin',  linspace(1.0e-9,  1.0e-8, 10), ...
  'L_dH_ext', linspace(1.0e-9,  1.0e-8, 10), ...
  'L_sH_ext', linspace(1.0e-9,  1.0e-8, 10), ...
  'L_gH_ext', linspace(1.0e-8,  1.0e-7, 10), ...
  'L_dL_ext', linspace(1.0e-9,  1.0e-8, 10), ...
  'L_sL_ext', linspace(1.0e-9,  1.0e-8, 10), ...
  'L_gL_ext', linspace(2.0e-9,  2.0e-8, 10), ...
  'L_Hwire',  linspace(2.5e-8,  2.5e-7, 10), ...
  'L_Lwire',  linspace(2.0e-9,  2.0e-8, 10)  ...
);

params = fieldnames(space);

emptySpaces = repmat(' ', 1, numel(space.(params{1}))+1); % needed by readtable

fileID = fopen(spaceFileName, 'w');
fprintf(fileID, "[BEGIN_SPACE]%s\n", emptySpaces);

for i = 1:numel(params)
    paramsValuesStr = mat2str(space.(params{1}));
    fprintf(fileID, "%s %s 0\n", params{i}, paramsValuesStr(2:end-1));
    fprintf(fileID, "DEFAULT %s %s\n\n", space.(params{1})(1), emptySpaces);

end

fprintf(fileID, "[END_SPACE]%s\n", emptySpaces);
fclose(fileID);

